### ISSUE TITLE
Computational Details

### ISSUE THREAD

**Issue by apsdehal** [woozzu/dong_iccv_2017#1]
Hi,

Thanks for creating this project.
I was trying to train this model and wanted to know the configuration details of the machine on which you trained this (GPU type and memory, CPU cores, RAM used, etc). Also, it would be great if you can tell how much time it took for you to train this model.

Thanks a lot.

**Comment by woozzu** [comment]
I trained this model on the machine that has Xeon CPU (4 cores), 32GB RAM, and GTX 1080 GPU. The training time was approximately 6 hours.

**Comment by apsdehal** [comment]
Thanks a lot for your help
