### ISSUE TITLE
Could you provide the pre-trained text embedding?

### ISSUE THREAD

**Issue by HelenMao** [woozzu/dong_iccv_2017#12]
Hi, thanks for your great implementation.
I meet some problems in training a visual-semantic embedding.
Would you mind directly offering the pre-trained text embedding so that I can directly train the model?
Thanks!

**Comment by woozzu** [comment]
@HelenMao Hi, you can access pre-trained embeddings below:
https://drive.google.com/open?id=0B9JkrC3TD6L1cXhERjNwaGNtbUU
https://drive.google.com/open?id=0B9JkrC3TD6L1R0ZwYjFMQXVObEE

**Comment by HelenMao** [comment]
Thanks a lot!
