### ISSUE TITLE
training model request

### ISSUE THREAD

**Issue by laxyon** [woozzu/dong_iccv_2017#15]
Hi, we are taking some experiments in different text guided image manipulation models. To be fair, could you provide your fine-tuned training model checkpoint file?

**Comment by woozzu** [comment]
Hi @laxyon, you can access the pre-trained weights in https://www.dropbox.com/sh/zr3i7k6xz0z435r/AABHfV5BN5Uz8sIXZuqspHZua?dl=0

**Comment by laxyon** [comment]
thank you so much
