### ISSUE TITLE
fasttext error! Couldn't not load_model after tried your fixed code!

### ISSUE THREAD

**Issue by jeffzjzhang** [woozzu/dong_iccv_2017#2]
Environment Azure NC6 56GB RAM Python2.7
after run './scripts/train_birds.sh', I got below error infomation:

Loading a pretrained fastText model...
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    word_embedding = fasttext.load_model(args.fasttext_model)
  File "fasttext/fasttext.pyx", line 154, in fasttext.fasttext.load_model
Exception: fastText: Cannot load /home/zijie/research/data/fastText/wiki.en.bin due to C++ extension failed to allocate the memory

**Comment by woozzu** [comment]
@csonder Did you clone the right branch of the repository? (feature/udpate-fasttext-to-f24a781-fix) If you did, you would have seen the following logs after 'make all'.
`test_load_invalid_skipgram_model (__main__.TestSkipgramModel) ... ok`
`test_load_skipgram_model (__main__.TestSkipgramModel) ... ok`
`test_train_skipgram_model (__main__.TestSkipgramModel) ... ERROR`
`test_train_skipgram_model_default (__main__.TestSkipgramModel) ... ERROR`
