### ISSUE TITLE
train_text_embedding.py the 'trainclasses_file' should be which .txt in config?

### ISSUE THREAD

**Issue by XinCynthia** [woozzu/dong_iccv_2017#4]
there is a classes.txt in datasets CUB_200_2011 which is from your link, I used the classes.py as the  'trainclasses_file' but get the error like below:
Traceback (most recent call last):
  File "/home/xin/PycharmProjects/colorchage2/train_text_embedding.py", line 81, in <module>
    std=[0.229, 0.224, 0.225])
  File "/home/xin/PycharmProjects/colorchage2/data.py", line 31, in __init__
    self.data = self._load_dataset(img_root, caption_root, classes_fllename, word_embedding)
  File "/home/xin/PycharmProjects/colorchage2/data.py", line 39, in _load_dataset
    filenames = os.listdir(os.path.join(caption_root, cls))
OSError: [Errno 2] No such file or directory: '/home/xin/PycharmProjects/colorchage2/datasets/CUB_200_2011/cub_icml/1 001.Black_footed_Albatross'
I think it is because there are count numbers at the first place of every row in classes.txt, so it is not suitable to use this file.
so where you get the 'trainclasses_file'? can you give a link?

**Comment by woozzu** [comment]
Probably, it's contained in the caption data for each dataset.

**Comment by XinCynthia** [comment]
Thank you I find it!
