### ISSUE TITLE
Can I train a text encoder without pretrain embedding

### ISSUE THREAD

**Issue by Ereebay** [woozzu/dong_iccv_2017#7]
Can I train a text encoder without a pretrained embedding?  I am wondering the usage of fast text

**Comment by woozzu** [comment]
@Ereebay Yes, you can train you own word embedding without using fasttext. e.g. one-hot vector encoding

**Comment by Ereebay** [comment]
So if I want to train a text encoder,  I must train a word embedding first. Right?`
